---
apiVersion: projectriff.io/v1alpha1
kind: Invoker
metadata:
  name: php
spec:
  version: 0.0.1
  matchers:
  - "*.php"
  functionTemplate:
    spec:
      protocol: http
  files:
  - path: Dockerfile
    template: |
      FROM gcr.io/cf-spring-funkytown/fbiville-php-invoker:{{.InvokerVersion}}
      RUN mkdir /functions
      ADD {{.Artifact}} /functions/
      ENV FUNCTION_URI /functions/{{.ArtifactBase}}
  doc: |
    {{.Process}} the function based on the executable command specified as the filename, using the name
    and version specified for the function image repository and tag.
    
    For example, from a directory named 'echo' containing a function 'echo.php', you can simply type :
    
        riff {{.Command}} -a echo.php
    
    to {{.Result}}.